### PR TITLE
Laravel 5.6 Shift

### PR DESCRIPTION
**Pull request by pvankouteren**
This pull request includes the changes for upgrading to Laravel 5.6. Feel free to commit any additional changes to the `shift-38589` branch.

**Before merging**, you need to:

- Checkout the `shift-38589` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.6
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by pvankouteren** [comment]
:information_source: Laravel 5.6 introduced a _logging_ configuration file. You should ensure the `log` and `log_level` settings previously in the `config/app.php` are now set in `config/logging.php`.

**Comment by pvankouteren** [comment]
:warning: Since you are upgrading from an older version of Laravel, Shift defaulted your customized configuration files to improve the automation in your next Shift. This was done in [a separate commit](https://github.com/Ecodenl/Woningdossier/pull/656/commits/51ec49a49afd186869f588b50255bf9c5312d2b0?w=1) so you may easily reference the changes and backfill your customizations once you are done _Shifting_. Future Shifts (Laravel 6+) will preserve your true customizations by merging them back in with the defaults.

- [ ] config/auth.php
- [ ] config/broadcasting.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/filesystems.php
- [ ] config/mail.php
- [ ] config/queue.php
- [ ] config/services.php
- [ ] config/session.php
- [ ] config/view.php

**Comment by pvankouteren** [comment]
:information_source: Laravel 5.6 recommends using the [_Hash_ facade](https://laravel.com/docs/5.6/hashing) instead of the `bcrypt` function directly as it provides greater flexibility for additional hashing algorithms and leverages the new `hashing.php` configuration.

Since Laravel uses the `bcrypt` algorithm by default, Shift [converted your instances](https://github.com/Ecodenl/Woningdossier/pull/656/commits/d34858a94c50996ac9998fcc092c93a789e82e56?w=1) of `bcrypt()` to `Hash::make()`.

**Comment by pvankouteren** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 4.0. If you are directly interacting with any Symfony components, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/4.0/CHANGELOG-4.0.md) for additional changes.

**Comment by pvankouteren** [comment]
:information_source: The `optimize` command was deprecated in Laravel 5.5 and removed in Laravel 5.6. However, it is re-added in Laravel 5.7. If you are using this command, it may be temporarily unavailable.

**Comment by pvankouteren** [comment]
:information_source: In Laravel 5.6, Blade will double encode special characters by default. If you would like to maintain the previous behavior of preventing double encoding, you may add `Blade::withoutDoubleEncoding()` to your AppServiceProvider `boot` method.

**Comment by pvankouteren** [comment]
:information_source: Laravel 5.6 uses Bootstrap 4 by default. Shift did not update your front-end resources or dependencies as this could impact your UI. If you are using Bootstrap and wish to continue using Bootstrap 3, you should add `Paginator::useBootstrapThree()` to your _AppServiceProvider_ `boot` method.

**Comment by frogeyedman** [comment]
> ⚠️ Since you are upgrading from an older version of Laravel, Shift defaulted your customized configuration files to improve the automation in your next Shift. This was done in [a separate commit](https://github.com/Ecodenl/Woningdossier/pull/656/commits/51ec49a49afd186869f588b50255bf9c5312d2b0?w=1) so you may easily reference the changes and backfill your customizations once you are done _Shifting_. Future Shifts (Laravel 6+) will preserve your true customizations by merging them back in with the defaults.
> 
>     * [x]  config/auth.php
> 
>     * [x]  config/broadcasting.php
> 
>     * [ ]  config/cache.php
> 
>     * [x]  config/database.php
> 
>     * [x]  config/filesystems.php
> 
>     * [x]  config/mail.php
> 
>     * [x]  config/queue.php
> 
>     * [x]  config/services.php
> 
>     * [x]  config/session.php
> 
>     * [x]  config/view.php

@pvankouteren check cache.php for prefix.

**Pull request merged**
