### PR TITLE
Laravel 5.7 Shift

### PR DESCRIPTION
**Pull request by pvankouteren**
This pull request includes the changes for upgrading to Laravel 5.7. Feel free to commit any additional changes to the `shift-38751` branch.

**Before merging**, you need to:

- Checkout the `shift-38751` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.7
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by pvankouteren** [comment]
:warning: Laravel 5.7 changed the environment variable `QUEUE_DRIVER` to `QUEUE_CONNECTION`. Shift automated this change. However, you should review this server configuration or `.env` files outside your project to see if they need to be changed.

**Comment by pvankouteren** [comment]
:warning: Since you are upgrading from an older version of Laravel, Shift defaulted your customized configuration files to improve the automation in your next Shift. This was done in [a separate commit](https://github.com/Ecodenl/Woningdossier/pull/661/commits/243dad3b23219edf3a14931da6a37e6704360f9d?w=1) so you may easily reference the changes and backfill your customizations once you are done _Shifting_. Future Shifts (Laravel 6+) will preserve your true customizations by merging them back in with the defaults.

- [ ] config/auth.php
- [ ] config/broadcasting.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/filesystems.php
- [ ] config/hashing.php
- [ ] config/logging.php
- [ ] config/mail.php
- [ ] config/queue.php
- [ ] config/services.php
- [ ] config/session.php
- [ ] config/view.php

**Comment by pvankouteren** [comment]
:information_source: Laravel 5.7 removed the Blade "or" operator in favor of PHP's built-in `??` "null coalesce" operator.

Shift automated this change. However, your application may still contain instances of `or` if you are using Blade syntax outside of the `resources` folder.

**Comment by pvankouteren** [comment]
:warning: The `sendResetResponse` method of the `ResetsPasswords` trait now receives the incoming `Illuminate\Http\Request` as its first argument. Shift detected methods matching this signature in the following files. You should review these methods to see if this new `$request` parameter needs to be added.

- [ ] app/Http/Controllers/Cooperation/Auth/ResetPasswordController.php

**Comment by pvankouteren** [comment]
:information_source: Laravel 5.7 now supports email verification when users register for your application. If you have implemented this feature yourself you may now be able to take advantage of this native functionality. For more details, review the documentation on [Email Verification](https://laravel.com/docs/5.7/verification).

**Comment by frogeyedman** [comment]
> ⚠️ Laravel 5.7 changed the environment variable `QUEUE_DRIVER` to `QUEUE_CONNECTION`. Shift automated this change. However, you should review this server configuration or `.env` files outside your project to see if they need to be changed.

@pvankouteren change .env's on server

**Comment by frogeyedman** [comment]
> ℹ️ Laravel 5.7 removed the `resources/assets` folder in favor of placing its sub-folders directly under `resources`. Shift moved these for you automatically. However, you may need to update the paths configured in your frontend build tool (e.g. `webpack.mix.js`) to reflect this new structure.
> 
> While Shift encourages a fully upgraded application, this new structure is not required. If this change significantly impacts your frontend build process, you can revert this commit.

Seems ok

**Pull request merged**
