### PR TITLE
Laravel 6.x Shift

### PR DESCRIPTION
**Pull request by pvankouteren**
This pull request includes the changes for upgrading to Laravel 6.x. Feel free to commit any additional changes to the `shift-39552` branch.

**Before merging**, you need to:

- Checkout the `shift-39552` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 6
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by pvankouteren** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 6 versions](https://github.com/laravel-shift/laravel-6.0/) and merge any changes:

- [ ] app/Http/Kernel.php
- [ ] resources/lang/en/passwords.php
- [ ] resources/lang/en/validation.php

**Comment by pvankouteren** [comment]
:warning: Laravel 6.x consolidated references to `/home` as a constant within the `RouteServiceProvider`. This makes it easier to maintain and change in a single place.

Shift [automated this change](https://github.com/Ecodenl/Woningdossier/pull/672/commits/54f1e1ccd04dea8d3363f578ad507416b6ae4a95?w=1), but could not upgrade the following files since they differed from the default Laravel version. You should compare these files against the [default Laravel 6 versions](https://github.com/laravel-shift/laravel-6.0/) and merge this change:

- [ ] app/Http/Middleware/RedirectIfAuthenticated.php

**Comment by pvankouteren** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables. This should make [maintaining your config files easier](https://jasonmccreary.me/articles/maintaining-laravel-config-files/).

You should [review this commit](https://github.com/Ecodenl/Woningdossier/pull/672/commits/98c8d892608ba5a437dbcc4810a1993bb2f1555e?w=1) for any additional customizations. If you have a lot of customizations, you may wish to undo this commit with `git revert` and make these [config file changes](https://github.com/laravel-shift/laravel-5.8/pull/6/commits/b3cc4626a4cd393b14a1b42c404ae8e6efc06339) manually.

**Comment by pvankouteren** [comment]
:information_source: Laravel 6 changed the default Redis client from `predis` to `phpredis`. You may keep using `predis` by setting `REDIS_CLIENT=predis` for your environment.

**Comment by pvankouteren** [comment]
:information_source: Shift [updated your dependencies](https://github.com/Ecodenl/Woningdossier/pull/672/commits/1f36e2e32515fab528286c5299f077fb332c1c3c?w=1) for Laravel 6. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 6.

Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by pvankouteren** [comment]
:warning: In Laravel 6, the `update` method of the `BelongsTo` relationship no longer provides mass assignment protection or fires Eloquent events. If you wish to preserve this behavior, you should call `update` on the model itself.

```php
// no mass assignment protection or events...
$post->user()->update(['foo' => 'bar']);

// mass assignment protection and events...
$post->user->update(['foo' => 'bar']);
```

Shift found potential uses of the `update` method in:

- [ ] app/Http/Controllers/Cooperation/MyAccount/SettingsController.php
- [ ] app/Listeners/GiveCoachesBuildingPermission.php
- [ ] app/Listeners/RevokeBuildingPermissionForCoaches.php

**Comment by pvankouteren** [comment]
:information_source: The Eloquent model's `toArray()` method will now cast any attributes that implement `Illuminate\Contracts\Support\Arrayable` to an array. While unlikely to impact your application, this change could effect code which relies upon the previous data type or output.

**Comment by pvankouteren** [comment]
:warning: Laravel 6 changed several of the core contracts with new implementations and methods. You should review the _Upgrade Guide_ for more detail on these respective changes:

- [Illuminate\Contracts\Auth\MustVerifyEmail](https://laravel.com/docs/6.x/upgrade#mustverifyemail-contract)


Shift found references to these contracts within:

- [ ] app/Http/Middleware/EnsureEmailIsVerified.php
- [ ] app/Models/Account.php

**Comment by pvankouteren** [comment]
:warning: In Laravel 6 the `PasswordBroker` no longer restricts or validates passwords. This is now done in the `ResetPasswordController`. You should review the following references to ensure you validate all passwords before passing them to the broker.

- [ ] app/Auth/Passwords/PasswordBrokerManager.php

**Comment by pvankouteren** [comment]
:information_source: Laravel 6 now requires Carbon 2. While Shift reviewed your application for common breaking changes, you may want to review the [Carbon 2 migration notes](https://carbon.nesbot.com/docs/#api-carbon-2) for additional changes.

**Comment by pvankouteren** [comment]
:information_source: Laravel 6 made some changes to the email verification routes. First, to prevent CSRF attacks the `email/resend` has been changed from a `GET` to a `POST` route. Second, a `hash` parameter was added to the `email/verify` route.

If you were calling these routes in your application code, you will need to adjust the requests accordingly.

**Comment by pvankouteren** [comment]
:warning: Previous versions of Laravel would bind parameters passed to the URL helper methods as placeholder values even if the names mismatched. In Laravel 6, named parameters not matching placeholders are attached to the query string instead.

Shift detected the following `route()` and `action()` calls passing named parameters you should review to ensure they match the route placeholder name.

- [ ] app/Exceptions/Handler.php
- [ ] app/Http/Controllers/Cooperation/Admin/ExampleBuildingController.php
- [ ] app/Http/Controllers/Cooperation/Admin/SuperAdmin/Cooperation/CooperationAdminController.php
- [ ] app/Http/Controllers/Cooperation/Admin/SuperAdmin/Cooperation/CoordinatorController.php
- [ ] app/Http/Controllers/Cooperation/Admin/SuperAdmin/Cooperation/HomeController.php
- [ ] app/Http/Controllers/Cooperation/MyAccount/MessagesController.php
- [ ] app/Http/Controllers/Cooperation/RecoverOldEmailController.php
- [ ] resources/views/cooperation/admin/buildings/show.blade.php
- [ ] resources/views/cooperation/admin/choose-roles.blade.php
- [ ] resources/views/cooperation/admin/coach/buildings/index.blade.php
- [ ] resources/views/cooperation/admin/cooperation/coaches/index.blade.php
- [ ] resources/views/cooperation/admin/cooperation/coaches/show.blade.php
- [ ] resources/views/cooperation/admin/cooperation/questionnaires/index.blade.php
- [ ] resources/views/cooperation/admin/cooperation/questionnaires/questionnaire-editor.blade.php
- [ ] resources/views/cooperation/admin/cooperation/reports/index.blade.php
- [ ] resources/views/cooperation/admin/cooperation/reports/parts/file-type-questionnaire-table-row.blade.php
- [ ] resources/views/cooperation/admin/cooperation/users/index.blade.php
- [ ] resources/views/cooperation/admin/example-buildings/edit.blade.php
- [ ] resources/views/cooperation/admin/example-buildings/index.blade.php
- [ ] resources/views/cooperation/admin/layouts/navbar.blade.php
- [ ] resources/views/cooperation/admin/layouts/navbar/role-switcher.blade.php
- [ ] resources/views/cooperation/admin/layouts/sidebar-menu.blade.php
- [ ] resources/views/cooperation/admin/messages/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/cooperation-admin/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/coordinator/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/home/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/users/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/cooperations/users/show.blade.php
- [ ] resources/views/cooperation/admin/super-admin/translations/edit.blade.php
- [ ] resources/views/cooperation/admin/super-admin/translations/index.blade.php
- [ ] resources/views/cooperation/admin/super-admin/users/show.blade.php
- [ ] resources/views/cooperation/auth/login.blade.php
- [ ] resources/views/cooperation/auth/passwords/request/index.blade.php
- [ ] resources/views/cooperation/auth/passwords/reset/show.blade.php
- [ ] resources/views/cooperation/auth/register.blade.php
- [ ] resources/views/cooperation/conversation-requests/index.blade.php
- [ ] resources/views/cooperation/create-building/index.blade.php
- [ ] resources/views/cooperation/home/index.blade.php
- [ ] resources/views/cooperation/layouts/navbar.blade.php
- [ ] resources/views/cooperation/mail/user/associated/text.blade.php
- [ ] resources/views/cooperation/mail/user/associated/view.blade.php
- [ ] resources/views/cooperation/mail/user/changed-email/text.blade.php
- [ ] resources/views/cooperation/mail/user/changed-email/view.blade.php
- [ ] resources/views/cooperation/mail/user/confirm-account/text.blade.php
- [ ] resources/views/cooperation/mail/user/confirm-account/view.blade.php
- [ ] resources/views/cooperation/mail/user/created/text.blade.php
- [ ] resources/views/cooperation/mail/user/created/view.blade.php
- [ ] resources/views/cooperation/mail/user/password-reset-request/text.blade.php
- [ ] resources/views/cooperation/mail/user/password-reset-request/view.blade.php
- [ ] resources/views/cooperation/mail/user/unread-message-count/text.blade.php
- [ ] resources/views/cooperation/mail/user/unread-message-count/view.blade.php
- [ ] resources/views/cooperation/messages/parts/private-public-modal.blade.php
- [ ] resources/views/cooperation/my-account/index.blade.php
- [ ] resources/views/cooperation/my-account/layouts/components/chat-input.blade.php
- [ ] resources/views/cooperation/tool/floor-insulation/index.blade.php
- [ ] resources/views/cooperation/tool/heat-pump/index.blade.php
- [ ] resources/views/cooperation/tool/heater/index.blade.php
- [ ] resources/views/cooperation/tool/hr-boiler/index.blade.php
- [ ] resources/views/cooperation/tool/includes/top-alerts.blade.php
- [ ] resources/views/cooperation/tool/index.blade.php
- [ ] resources/views/cooperation/tool/insulated-glazing/index.blade.php
- [ ] resources/views/cooperation/tool/layout.blade.php
- [ ] resources/views/cooperation/tool/my-plan/index.blade.php
- [ ] resources/views/cooperation/tool/my-plan/parts/my-plan-form.blade.php
- [ ] resources/views/cooperation/tool/parts/progress.blade.php
- [ ] resources/views/cooperation/tool/roof-insulation/index.blade.php
- [ ] resources/views/cooperation/tool/solar-panels/index.blade.php
- [ ] resources/views/cooperation/tool/ventilation-information/index.blade.php
- [ ] resources/views/cooperation/tool/ventilation/index.blade.php
- [ ] resources/views/cooperation/tool/wall-insulation/index.blade.php
- [ ] resources/views/test.blade.php

**Comment by pvankouteren** [comment]
:information_source: Laravel 6 made [performance optimizations](https://github.com/laravel/framework/pull/28153) for _integer_ key types. If you are using a _string_ as your model's primary key, you may set the `$keyType` property on your model.

```php
/**
 * The "type" of the primary key ID.
 *
 * @var string
 */
protected $keyType = 'string';
```

**Comment by pvankouteren** [comment]
:information_source: The `mandrill` and `sparkpost` mail drivers, as well as the `rackspace` storage driver were removed in Laravel 6. If you were using these drivers, you may adopt a community maintained package which provides the driver.

**Comment by pvankouteren** [comment]
:information_source: Previous versions of Laravel would retry jobs indefinitely. Beginning with Laravel 6, the `php artisan queue:work` now tries a job one time by default. If you want to force jobs to be tried indefinitely, you may pass the `--tries=0` option.

**Comment by frogeyedman** [comment]
> ℹ️ Laravel 6 changed the default Redis client from `predis` to `phpredis`. You may keep using `predis` by setting `REDIS_CLIENT=predis` for your environment.

Check if applicable to us.

**Pull request merged**
