### PR TITLE
Laravel 7.x Shift

### PR DESCRIPTION
**Pull request by pvankouteren**
This pull request includes the changes for upgrading to Laravel 7.x. Feel free to commit any additional changes to the `shift-73460` branch.

**Before merging**, you need to:

- Checkout the `shift-73460` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by pvankouteren** [comment]
:warning: Laravel 7 adds CORS middleware and defaults the `middlewarePriority` internally so you only need to overwrite this property for customizations.

Shift attempted to automate these changes, but you should compare your `app/Http/Kernel.php`  with the [default Laravel 7 version](https://github.com/laravel-shift/laravel-7.x/blob/master/app/Http/Kernel.php) to finalize any changes.

**Comment by pvankouteren** [comment]
:information_source: Laravel 7 upgraded to Symfony 5 which passes instances of the `Throwable` interface instead of `Exception` instances to core components like the `Exceptions\Handler`.

Shift [automated this change](https://github.com/Ecodenl/Woningdossier/pull/1166/commits/a7775b489be7a9a211fb575347b6c0596b32b83f?w=1). However, if you receive a `Throwable` type mismatch error there may be additional references you need to convert.

**Comment by pvankouteren** [comment]
:information_source: Laravel 7 moved the Authentication components into a separate [`laravel/ui` package](https://github.com/laravel/ui), which includes the _make_ commands as well as the traits related to authentication.

Shift added this dependency for convenience. However, if you do not plan to use the Authentication components, you may remove this dependency as well as the `Auth` controllers from your application.

**Comment by pvankouteren** [comment]
:warning: Shift detected potential calls to the Eloquent `getOriginal` method. In Laravel 7, this method now casts model data. If you need the raw, uncast values, you may use the `getRawOriginal` method instead.

You should review these instances to see if they need to be converted to `getRawOriginal`.

- [ ] app/Traits/ToolSettingTrait.php

**Comment by pvankouteren** [comment]
:information_source: Shift [updated your dependencies](https://github.com/Ecodenl/Woningdossier/pull/1166/commits/cbdcd95b5158da02449a9ab7f817d4b548f8e227?w=1) for Laravel 7. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 7. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [darkaonline/l5-swagger](https://packagist.org/packages/darkaonline/l5-swagger)

**Comment by pvankouteren** [comment]
:warning: Laravel 7 added a `recentlyCreatedToken` method to the `Illuminate\Auth\Passwords\TokenRepositoryInterface` interface. If you are implementing this interface, you will need to update the class to add this new method.

Shift found references to this interface within:

- [ ] app/Auth/Passwords/DatabaseTokenRepository.php

**Comment by pvankouteren** [comment]
:warning: In Laravel 7, all of the `assertSee` methods now automatically escape the expected values.

If you were manually escaping the values passed to these methods, you no longer need do so. If you were asserting values containing HTML that should not be escaped, you may set the new `escaped` argument to `false`.

Shift found the instances of these assertions within:

- [ ] tests/Browser/ExampleTest.php
- [ ] tests/Browser/RegisterTest.php

**Comment by pvankouteren** [comment]
:warning: Shift found potential uses of the `different` validation rule. In Laravel 7, this rule will fail if one of the specified parameters is missing from the request. As this was likely the expected behavior, it should not affect your validation. Nonetheless you should be aware of this change.

**Comment by pvankouteren** [comment]
:warning: Laravel 7 uses a new date format when serializing models. The previous format was `2019-12-02 20:01:00`. Now, dates are serialized using an ISO-8601 compatible date format of `2019-12-02T20:01:00.283041Z` in `UTC`.

**This does not affect how dates are stored**. Only how they are serialized when using the `toArray` or `toJson` Eloquent methods.

If you need to preserve the previous format, you may override the `serializeDate` method on your model. Review the [Date Serialization](https://laravel.com/docs/7.x/upgrade#date-serialization) section of the _Upgrade Guide_ for more details.

**Comment by pvankouteren** [comment]
:warning: Laravel 7.x has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest version (Laravel 9.x).

For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Comment by frogeyedman** [comment]
This PR / shift is ok, and could be merged to develop-heat-pump.

**Pull request merged**
